version: '3'

services:

  database:
    image: 'bitnami/postgresql'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=gobarber
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  
  redis:
    image: redis:alpine    
    restart: always
    ports:
      - 6379:6379
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db  

volumes:
  postgresql_data:
    driver: local