// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"backend-gobarber-golang/internal/infra/repository"
	"backend-gobarber-golang/internal/infra/storage"
	"backend-gobarber-golang/internal/pkg/database"
	"backend-gobarber-golang/internal/service"
)

// Injectors from wire.go:

func InitializeUserRepository() *repository.UserRepository {
	db := database.GetDatabase()
	userRepository := repository.NewUserRepository(db)
	return userRepository
}

func InitializeCreateUsersService() *service.CreateUsersService {
	userRepository := InitializeUserRepository()
	createUsersService := service.NewCreateUsersService(userRepository)
	return createUsersService
}

func InitializeShowProfileService() *service.ShowProfileService {
	userRepository := InitializeUserRepository()
	showProfileService := service.NewShowProfileService(userRepository)
	return showProfileService
}

func InitializeUpdateProfileService() *service.UpdateProfileService {
	userRepository := InitializeUserRepository()
	updateProfileService := service.NewUpdateProfileService(userRepository)
	return updateProfileService
}

func InitializeJWTService() *service.JWTService {
	jwtService := service.NewJWTService()
	return jwtService
}

func InitializeAuthenticateUserService() *service.AuthenticateUserService {
	userRepository := InitializeUserRepository()
	jwtService := InitializeJWTService()
	authenticateUserService := service.NewAuthenticateUserService(userRepository, jwtService)
	return authenticateUserService
}

func InitializeDiskStorageProvider() *storage.DiskStorageProvider {
	diskStorageProvider := storage.NewDiskStorageProvider()
	return diskStorageProvider
}

func InitializeUpdateUserAvatarService() *service.UpdateUserAvatarService {
	userRepository := InitializeUserRepository()
	diskStorageProvider := InitializeDiskStorageProvider()
	updateUserAvatarService := service.NewUpdateUserAvatarService(userRepository, diskStorageProvider)
	return updateUserAvatarService
}
