app:
  name: gobarber-golang
  version: 1.0.0

http:
  port: ${HTTP_PORT}

logger:
  log_level: ${LOG_LEVEL}

cache:
  url: ${REDIS_URL}
  port: ${REDIS_PORT}
  db: ${REDIS_DB}
  password:

application:
  app_web_url: http://localhost:8080/gobarber-golang

postgres:
  host: ${HOST_DB}
  port: ${PORT_DB}
  username: ${USERNAME_DB}
  password: ${PASSWORD_DB}
  dbname: gobarber
  schema: gobarber_golang
  maxIdleConns: 10
  MaxOpenConns: 100

mongodb:
  host: ${HOST_MONGODB}
  port: ${PORT_MONGODB}
  dbname: ${DATABASE_MONGODB}
  username: ${USERNAME_MONGODB}
  password: ${PASSWORD_MONGODB}

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}

etherealMail:
  smtp:
    host: ${HOST_ETHEREAL_MAIL}
    port: ${PORT_ETHEREAL_MAIL}
    username: ${USERNAME_ETHEREAL_MAIL}
    password: ${PASSWORD_ETHEREAL_MAIL}

